spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music_shelf?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: '12345678'
    hikari:
      initialization-fail-timeout: 0 #커넥션 초기화 실패 시 유효성 검사 시도

    #JPA 설정
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create #[create] [create-drop] [update] [validate] [none] 상황에 맞게 사용하기
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      use-new-id-generator-mappings: false
      show-sql: true  #설정시 JPA 쿼리문 확인 가능
    properties:
      hibernate.format_sql: true  #Hibernate가 동작하면서 발생한 SQL의 가독성을 높여 줌 ############
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect  #DB 바꿀 시 이 설정만 바꿔주면 각 DB에 맞는 SQL 문법으로 바꿔 줌

  #로그 레벨 설정
  logging:
    level:
      org.hibernate.SQL: debug #로그에 SQL 출력
